<a href="https://colab.research.google.com/github/maliaheupel/ds2002-fa2/blob/main/02-sql/2026_09_18_%E2%80%94_Pandas_Challenge_%E2%80%94_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DS2002 · Pandas Challenge

**Lab — 2026-09-18 · Fall 2026**  

---

## Lab 04 — Pandas Challenge

Four hundred generated orders. Each question builds toward a demand report you could hand a vendor.

The data is seeded, so everyone's numbers should match. That is deliberate: if your total revenue differs from your neighbor's, one of you has a bug, and the assertions at the end will tell you which.

Every answer needs the number **and** a sentence saying what it means. A cell that prints `4218.5` with no interpretation is half an answer.

In [1]:
import pandas as pd, numpy as np
rng = np.random.default_rng(4)
n = 400
df = pd.DataFrame({
    'vendor_id': rng.choice(['V-01','V-05','V-10','V-18'], n),
    'category': rng.choice(['Food','Merch','RainGear','Drink'], n, p=[.5,.2,.1,.2]),
    'qty': rng.integers(1, 4, n),
    'price': rng.choice([4.5, 6.0, 7.5, 12.0, 24.0], n),
})
df.head()

  vendor_id  category  qty  price
0      V-10     Drink    2   24.0
1      V-18  RainGear    1   12.0
2      V-18     Drink    3    4.5
3      V-10      Food    2   12.0
4      V-18     Drink    3    7.5

### Q1 — Add `revenue`, then report total revenue and total units.

*Expected: 400 rows, and revenue should land between $8,000 and $9,000.*

In [13]:
# TODO
df['revenue'] = df['qty'] * df['price']

total_rev = df['revenue'].sum()
total_units = df['qty'].sum()

print(df['revenue'])
print('dollar amount of revenue = ', total_rev)
print('item total to make up revenue',total_units)
print("There were 400 orders in total, in which 783 items were sold to bring in $8520 worth of revenue.")

0      48.0
1      12.0
2      13.5
3      24.0
4      22.5
       ...
395    12.0
396    48.0
397    22.5
398    48.0
399     7.5
Name: revenue, Length: 400, dtype: float64
dollar amount of revenue =  8520.0
item total to make up revenue 783
There were 400 orders in total, in which 783 items were sold to bring in $8520 woeth of revenue.

### Q2 — Revenue by category, highest to lowest.

Include the share of total as a percentage in the same table.

In [15]:
# TODO
by_category = df.groupby('category')['revenue'].sum().reset_index()

by_category['share_pct'] = (by_category['revenue'] / total_rev) * 100

by_category = by_category.sort_values(by='revenue', ascending=False)

print(by_category)

print("Food had the highest revenue of $4293.0 which made up about 50% of total revenue")

   category  revenue  share_pct
1      Food   4293.0  50.387324
2     Merch   1771.5  20.792254
0     Drink   1554.0  18.239437
3  RainGear    901.5  10.580986
Food had the highest revenue of $4293.0 which made up about 50% of total revenue

### Q3 — Which vendor has the highest *average* order revenue?

Report the average alongside the order count for each vendor. A high average on twelve orders is a different claim from a high average on two hundred.

In [20]:
# TODO
vendor_stats = df.groupby('vendor_id').agg(
    avg_revenue=('revenue', 'mean'),
    order_count=('revenue', 'count')
).reset_index()

vendor_stats = vendor_stats.sort_values(by='avg_revenue', ascending=False)
print(vendor_stats)
print("The V-01 vendor had the highest average order revenue of $22.60 across 94 orders.")

  vendor_id  avg_revenue  order_count
0      V-01    22.595745           94
3      V-18    21.750000          108
1      V-05    20.580645           93
2      V-10    20.314286          105
The V-01 vendor had the highest average order revenue of $22.60 across 94 orders.

### Q4 — What share of revenue comes from Merch?

Print it as a percentage rounded to one decimal.

In [29]:
# TODO
merch_revenue = df[df['category'] == 'Merch']['revenue'].sum()
merch_share = (merch_revenue / total_rev) * 100
print(round(merch_share, 1))
print("Merch makes up 20.8% of total revenue")

20.8
Merch makes up 20.8% of total revenue

### Q5 — Join in the vendor names.

The frame only has `vendor_id`. Merge the lookup below so your report is readable.

**Requirements:** left join, `validate='many_to_one'`, and prove the row count and revenue total did not change. One vendor id in the orders is not in this lookup — find it, and decide what to do about it.

In [40]:
vendor_names = pd.DataFrame({
    'vendor_id': ['V-01', 'V-05', 'V-10'],
    'vendor_name': ['Hoos Burgers', 'Rotunda Tacos', 'Cav Merch North'],
})

# TODO: merge, validate, and report the unmatched vendor
joined = pd.merge(df, vendor_names, on='vendor_id', how='left', validate='many_to_one')

print("Rows match:", len(joined) == len(df))
print("Revenue matches:", joined['revenue'].sum() == df['revenue'].sum())

missing_id = joined[joined['vendor_name'].isna()]['vendor_id'].unique()
print("Missing vendor:", missing_id)
joined['vendor_name'] = joined['vendor_name'].fillna('Unknown')
print(joined)
print("The missing vendor was V-18 and is now []")

Rows match: True
Revenue matches: True
Missing vendor: ['V-18']
    vendor_id  category  qty  price  revenue      vendor_name
0        V-10     Drink    2   24.0     48.0  Cav Merch North
1        V-18  RainGear    1   12.0     12.0          Unknown
2        V-18     Drink    3    4.5     13.5          Unknown
3        V-10      Food    2   12.0     24.0  Cav Merch North
4        V-18     Drink    3    7.5     22.5          Unknown
..        ...       ...  ...    ...      ...              ...
395      V-18     Merch    1   12.0     12.0          Unknown
396      V-01     Merch    2   24.0     48.0     Hoos Burgers
397      V-10      Food    3    7.5     22.5  Cav Merch North
398      V-18     Merch    2   24.0     48.0          Unknown
399      V-10     Drink    1    7.5      7.5  Cav Merch North

[400 rows x 6 columns]
The missing vendor was V-18 and is now []

**The unmatched vendor, and what I did about it:** _..._

The unmatched vendor is V-18 and i filled in the NaN value to be Unknown, so that we could still see the order records and its impact on the total revenue, while making it clearer that we don't know exactly who the vendor is.

### Q6 — A pivot table: vendors down the side, categories across the top, revenue in the cells.

Add row and column totals so it reads as a report rather than a grid of numbers.

In [51]:
# TODO
pivot_table = pd.pivot_table(
    joined,
    values='revenue',
    index='vendor_name',
    columns='category',
    aggfunc='sum',
    margins=True,
    margins_name='Total'
)
print("Creates a pivot table with the vendors and the different categories")
pivot_table

Creates a pivot table with the vendors and the different categories

category          Drink    Food   Merch  RainGear   Total
vendor_name
Cav Merch North   502.5  1054.5   400.5     175.5  2133.0
Hoos Burgers      171.0  1338.0   373.5     241.5  2124.0
Rotunda Tacos     298.5   882.0   489.0     244.5  1914.0
Unknown           582.0  1018.5   508.5     240.0  2349.0
Total            1554.0  4293.0  1771.5     901.5  8520.0

### Q7 — Validate your work

**TODO:** uncomment and make these pass. Assign your results to the named variables as you go.

In [52]:
assert len(df) == 400
assert 8000 < df['revenue'].sum() < 9000, df['revenue'].sum()
assert abs(by_category['revenue'].sum() - df['revenue'].sum()) < 0.01
assert len(joined) == len(df), 'the vendor merge changed the row count'
print('checks passed.')

checks passed.

### Write-up

**a)** What would you tell these vendors to do differently next game? One paragraph, with at least two numbers from your report in it.

**b)** Which of your seven answers is the least trustworthy, and why? Point at a specific weakness — a small group size, an unmatched vendor, a category that is really two things.



```
# This is formatted as code
```

a) The vendors should allocate more inventory to food, since it generated about 50% of total revenue, around 4293 dollars. Some items such Rain gear brought in only about $900, which is significantly less. Vendors would benefit more if they stocked up on more food and drinks to maximize profits, while minimizing the amount unsold, low-performing items.

b)Question 3 is the least trustworthy, since it groups together all food and drinks, and does not break them down further by price for example. This makes it least trustworthy because you cannot see what food items specifically made the most profit, or were the most popular, so that hides what the consumers specifically wanted.